services:
  php8.2:
    volumes:
      - ./:/app:delegated
      - ./.vendor/php8.2:/app/vendor
    build:
      context: ./docker/8.2
      target: base

  debug8.2:
    extends:
      service: php8.2
    volumes:
      - ./:/app:delegated
      - ./docker/8.2:/usr/local/etc/php
      - ./.vendor/php8.2:/app/vendor
    build:
      target: debug

  composer8.2:
    extends:
      service: php8.2
    volumes:
      - ./:/app:delegated
      - ./.vendor/php8.2:/app/vendor
    build:
      target: composer